/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package mx.edu.itcelaya.ecommerceproducts;

public class Customer {
	private java.lang.String last_name;
	public java.lang.String getLast_name() {
		return last_name;
	}
	private java.lang.String first_name;
	public java.lang.String getFirst_name() {
		return first_name;
	}
	private java.lang.Integer id;
 	public void setId(java.lang.Integer id) {
		this.id = id;
	}
	public java.lang.Integer getId() {
		return id;
	}
	private java.lang.String username;
	public java.lang.String getUsername() {
		return username;
	}
	private java.lang.String email;
	public java.lang.String getEmail() {
		return email;
	}
}