/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package mx.edu.itcelaya.ecommerceproducts;

public class ImageElement {
	private java.lang.String created_at;

 	public void setCreated_at(java.lang.String created_at) {
		this.created_at = created_at;
	}

	public java.lang.String getCreated_at() {
		return created_at;
	}

	private java.lang.String src;

 	public void setSrc(java.lang.String src) {
		this.src = src;
	}

	public java.lang.String getSrc() {
		return src;
	}

	private java.lang.Integer id;

 	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getId() {
		return id;
	}

	private java.lang.Integer position;

 	public void setPosition(java.lang.Integer position) {
		this.position = position;
	}

	public java.lang.Integer getPosition() {
		return position;
	}

	private java.lang.String updated_at;

 	public void setUpdated_at(java.lang.String updated_at) {
		this.updated_at = updated_at;
	}

	public java.lang.String getUpdated_at() {
		return updated_at;
	}

	private java.lang.String title;

 	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getTitle() {
		return title;
	}

	private java.lang.String alt;

 	public void setAlt(java.lang.String alt) {
		this.alt = alt;
	}

	public java.lang.String getAlt() {
		return alt;
	}

}