/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package mx.edu.itcelaya.ecommerceproducts;

public class Line_itemElement
{
	private Product_data product_data;
	public Product_data getProduct_data() {
		return product_data;
	}
	private java.lang.Integer id;
 	public void setId(java.lang.Integer id) {
		this.id = id;
	}
	public java.lang.Integer getId() {
		return id;
	}
	private java.lang.String price;
	public java.lang.String getPrice() {
		return price;
	}
	private java.lang.String name;
 	public void setName(java.lang.String name) {
		this.name = name;
	}
	public java.lang.String getName() {
		return name;
	}

}