/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package mx.edu.itcelaya.ecommerceproducts;

public class Ordenes {
	private OrderElement[] orders;
	public OrderElement[] getOrders() {
		return orders;
	}

}