/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package mx.edu.itcelaya.ecommerceproducts;

public class OrderElement {
	private java.lang.Integer order_number;
	public java.lang.Integer getOrder_number() {
		return order_number;
	}
	private java.lang.String status;
	public java.lang.String getStatus() {
		return status;
	}
	private Line_itemElement[] line_items;
	public Line_itemElement[] getLine_items() {
		return line_items;
	}
	private java.lang.String total;
	public java.lang.String getTotal() {
		return total;
	}
	private Customer customer;
	public Customer getCustomer() {
		return customer;
	}
	private Payment_details payment_details;
	public Payment_details getPayment_details() {
		return payment_details;
	}
	private java.lang.Integer total_line_items_quantity;
	public java.lang.Integer getTotal_line_items_quantity() {
		return total_line_items_quantity;
	}
	private java.lang.String created_at;
	public java.lang.String getCreated_at() {
		return created_at;
	}
	private java.lang.Integer id;
 	public void setId(java.lang.Integer id) {
		this.id = id;
	}
	public java.lang.Integer getId() {
		return id;
	}
}