/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package mx.edu.itcelaya.ecommerceproducts;

public class Payment_details {
	private java.lang.String method_title;
	public java.lang.String getMethod_title() {
		return method_title;

	}
}