/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package mx.edu.itcelaya.ecommerceproducts;

public class Product_data {
	private java.lang.Object stock_quantity;
	public java.lang.Object getStock_quantity() {
		return stock_quantity;
	}
	private java.lang.Boolean in_stock;
	public java.lang.Boolean getIn_stock() {
		return in_stock;
	}
	private ImageElement[] images;
	public ImageElement[] getImages() {
		return images;
	}
	private java.lang.Integer id;
 	public void setId(java.lang.Integer id) {
		this.id = id;
	}
	public java.lang.Integer getId() {
		return id;
	}
	private java.lang.String description;
	public java.lang.String getDescription() {
		return description;
	}

}